// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hotel.sql

package db

import (
	"context"
	"database/sql"
)

const createHotel = `-- name: CreateHotel :one
INSERT INTO hotels (manager_id, name, location, rating)
VALUES (?1, ?2, ?3, ?4)
RETURNING id
`

type CreateHotelParams struct {
	ManagerID int64
	Name      string
	Location  string
	Rating    sql.NullFloat64
}

func (q *Queries) CreateHotel(ctx context.Context, arg CreateHotelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createHotel,
		arg.ManagerID,
		arg.Name,
		arg.Location,
		arg.Rating,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateHotel = `-- name: UpdateHotel :one
UPDATE hotels
SET name = ?1,
    location = ?2,
    rating = ?3
WHERE id = ?4
RETURNING id
`

type UpdateHotelParams struct {
	Name     string
	Location string
	Rating   sql.NullFloat64
	ID       int64
}

func (q *Queries) UpdateHotel(ctx context.Context, arg UpdateHotelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateHotel,
		arg.Name,
		arg.Location,
		arg.Rating,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
